builds:
  - binary: check-longtransaction-cnt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ryuichi1208
    name: check-longtransaction-cnt
