on: [push, pull_request]
name: linter

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    steps:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc #v3.2.0
      with:
        version: v1.44.0
        args: --verbose
